package com.artmani.sod;

import com.artmani.sod.items.Group;
import com.artmani.sod.items.Student;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class Gui extends JFrame {
    private JPanel mainPanel;
    private JComboBox selectStudent;
    private JComboBox selectGroup;
    private JLabel groupNumberInfo;
    private JTextField groupNumberText;
    private JPanel groupInfoPanel;

    Gui() {
        super("Title");

        $$$setupUI$$$();
        setVisible(true);
        setContentPane(mainPanel);

        importGroupsToGui();
        importStudentsToGui();

        registerEvents();

        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        pack();

        setSize(720, 480);
        setResizable(false);


    }

    public void registerEvents() {

        /**
         * ActionListener для selectGroup
         **/
        selectGroup.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println(selectGroup.getSelectedItem());

                int groupID = (int) selectGroup.getSelectedItem();

                DefaultComboBoxModel comboBox = new DefaultComboBoxModel();
                for (Student s : Group.getGroupByID((int) selectGroup.getSelectedItem()).getStudents()) {
                    comboBox.addElement(s.getFullName());
                }
                selectStudent.setModel(comboBox);

                groupNumberText.setText("" + groupID);
            }
        });

        /**
         * ActionListener для selectStudent
         **/
        selectStudent.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });
    }

    public void importGroupsToGui() {
        DefaultComboBoxModel comboBox = new DefaultComboBoxModel();
        System.out.println(Group.groups.toString());
        for (Group g : Group.groups) {
            comboBox.addElement(g.getId());
        }
        selectGroup.setModel(comboBox);
    }


    public void importStudentsToGui() {

        DefaultComboBoxModel comboBox = new DefaultComboBoxModel();

        for (Student s : Group.getGroupByID((int) selectGroup.getSelectedItem()).getStudents()) {
            comboBox.addElement(s.getFullName());
        }
        selectStudent.setModel(comboBox);

    }


    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(4, 4, new Insets(0, 0, 0, 0), -1, -1));
        final Spacer spacer1 = new Spacer();
        mainPanel.add(spacer1, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        selectGroup = new JComboBox();
        selectGroup.setEditable(false);
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        selectGroup.setModel(defaultComboBoxModel1);
        mainPanel.add(selectGroup, new GridConstraints(0, 2, 2, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        selectStudent = new JComboBox();
        selectStudent.setEditable(false);
        final DefaultComboBoxModel defaultComboBoxModel2 = new DefaultComboBoxModel();
        selectStudent.setModel(defaultComboBoxModel2);
        mainPanel.add(selectStudent, new GridConstraints(0, 3, 2, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(120, -1), null, 0, false));
        groupInfoPanel = new JPanel();
        groupInfoPanel.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(groupInfoPanel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        groupNumberInfo = new JLabel();
        groupNumberInfo.setHorizontalTextPosition(2);
        groupNumberInfo.setText("Номер группы:");
        groupInfoPanel.add(groupNumberInfo, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(131, 29), null, 0, false));
        groupNumberText = new JTextField();
        groupNumberText.setEditable(false);
        groupNumberText.setText("choose");
        groupInfoPanel.add(groupNumberText, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(100, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }
}
